# Generated by Django 3.1.2 on 2020-10-26 13:58

from django.db import migrations

def forwards_func(apps, schema_editor):
    Libro = apps.get_model("core", "Libro")
    Autor = apps.get_model("core", "Autor")
    Articulo = apps.get_model("core", "Articulo")

    martin = Autor(nombre="George R. R. Martin")
    rowling = Autor(nombre="J. K. Rowling")

    for instance in [martin, rowling]:
        instance.save()

    articulo1 = Articulo(nombre="Articulo 1", autor=martin)
    articulo2 = Articulo(nombre="Articulo 2", autor=martin)
    articulo3 = Articulo(nombre="Articulo 3", autor=martin)
    articulo4 = Articulo(nombre="Articulo 4", autor=rowling)
    articulo5 = Articulo(nombre="Articulo 5", autor=rowling)

    for instance in [articulo1, articulo2, articulo3, articulo4, articulo5]:
        instance.save()

    libro1 = Libro(nombre="Juego de tronos", autor=martin, precio=100)
    libro2 = Libro(nombre="Choque de reyes", autor=martin, precio=100)
    libro3 = Libro(nombre="Tormenta de espadas", autor=martin, precio=100)
    libro4 = Libro(nombre="Harry Potter y la piedra filosofal", autor=rowling, precio=120)
    libro5 = Libro(nombre="Harry Potter y la cámara secreta", autor=rowling, precio=120)
    libro6 = Libro(nombre="Harry Potter y el prisionero de Azkaban", autor=rowling, precio=120)
    libro7 = Libro(nombre="Harry Potter y el cáliz de fuego", autor=rowling, precio=120)

    for instance in [libro1, libro2, libro3, libro4, libro5, libro6, libro7]:
        instance.save()

def reverse_func(apps, schema_editor):
    Libro = apps.get_model("core", "Libro")
    Autor = apps.get_model("core", "Autor")
    Articulo = apps.get_model("core", "Articulo")

    Libro.objects.all().delete()
    Autor.objects.all().delete()
    Articulo.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
